version: "3.8"
services:
  backend:
    image: bhattadparth2014/todo-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    image: bhattadparth2014/todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
