name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PWD }}

      - name: Build and Push Backend
        run: |
          docker build -t bhattadparth2014/todo-backend ./backend
          docker push bhattadparth2014/todo-backend

      - name: Build and Push Frontend
        run: |
          docker build -t bhattadparth2014/todo-frontend ./frontend
          docker push bhattadparth2014/todo-frontend

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.201.194.122
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ci-cd
            docker pull bhattadparth2014/todo-backend
            docker pull bhattadparth2014/todo-frontend
            docker-compose down
            docker-compose up -d --build
